- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable Grafana
  ansible.builtin.systemd:
    name: "{{ grafana_systemd_service }}"
    enabled: true
  become: true

- name: Start Grafana
  ansible.builtin.systemd:
    name: "{{ grafana_systemd_service }}"
    state: started
  become: true
